// AgentRecommendation entity definition
// Generated by AgriTwin Agent Factory

export const AgentRecommendation = {
  name: 'AgentRecommendation',
  schemaVersion: '1.0.0',
  fields: [
    { name: 'id', type: 'uuid', required: true },
    { name: 'cowId', type: 'uuid', required: true },
    { name: 'recommendationType', type: 'enum', values: ['treatment', 'monitoring', 'dietary', 'breeding', 'isolation'], required: true },
    { name: 'confidenceScore', type: 'decimal', required: true },
    { name: 'generatedAt', type: 'datetime', required: true },
    { name: 'rationale', type: 'text', required: false },
  ],
};

export default AgentRecommendation;
