// Cow entity definition
// Generated by AgriTwin Agent Factory

export const Cow = {
  name: 'Cow',
  schemaVersion: '1.0.0',
  fields: [
    { name: 'id', type: 'uuid', required: true },
    { name: 'earTag', type: 'string', required: true },
    { name: 'name', type: 'string', required: false },
    { name: 'birthDate', type: 'date', required: false },
    { name: 'herdId', type: 'uuid', required: true },
    { name: 'status', type: 'enum', values: ['active', 'sold', 'deceased'], required: true },
  ],
};

export default Cow;
