// HealthAlert entity definition
// Generated by AgriTwin Agent Factory

export const HealthAlert = {
  name: 'HealthAlert',
  schemaVersion: '1.0.0',
  fields: [
    { name: 'id', type: 'uuid', required: true },
    { name: 'cowId', type: 'uuid', required: true },
    { name: 'severity', type: 'enum', values: ['low', 'medium', 'high', 'critical'], required: true },
    { name: 'category', type: 'enum', values: ['mastitis', 'ketosis', 'lameness', 'fever', 'other'], required: true },
    { name: 'detectedAt', type: 'datetime', required: true },
    { name: 'resolvedAt', type: 'datetime', required: false },
  ],
};

export default HealthAlert;
