// Herd entity definition
// Generated by AgriTwin Agent Factory

export const Herd = {
  name: 'Herd',
  schemaVersion: '1.0.0',
  fields: [
    { name: 'id', type: 'uuid', required: true },
    { name: 'name', type: 'string', required: true },
    { name: 'farmId', type: 'uuid', required: true },
    { name: 'cowCount', type: 'integer', required: false },
  ],
};

export default Herd;
