// Shared entities for NemoClaw-agritwin-dairy-agentic-ai-platform-shared
// Generated by AgriTwin Agent Factory

export const entities = [
  {
    "name": "Cow",
    "schemaVersion": "1.0.0"
  },
  {
    "name": "Herd",
    "schemaVersion": "1.0.0"
  },
  {
    "name": "Sensor",
    "schemaVersion": "1.0.0"
  },
  {
    "name": "MilkYield",
    "schemaVersion": "1.0.0"
  },
  {
    "name": "HealthAlert",
    "schemaVersion": "1.0.0"
  },
  {
    "name": "AgentRecommendation",
    "schemaVersion": "1.0.0"
  }
];

export const ENTITY_NAMES = entities.map(e => e.name);
