// MilkYield entity definition
// Generated by AgriTwin Agent Factory

export const MilkYield = {
  name: 'MilkYield',
  schemaVersion: '1.0.0',
  fields: [
    { name: 'id', type: 'uuid', required: true },
    { name: 'cowId', type: 'uuid', required: true },
    { name: 'sessionAt', type: 'datetime', required: true },
    { name: 'volumeLitres', type: 'decimal', required: true },
    { name: 'qualityScore', type: 'decimal', required: false },
  ],
};

export default MilkYield;
