// Sensor entity definition
// Generated by AgriTwin Agent Factory

export const Sensor = {
  name: 'Sensor',
  schemaVersion: '1.0.0',
  fields: [
    { name: 'id', type: 'uuid', required: true },
    { name: 'cowId', type: 'uuid', required: true },
    { name: 'type', type: 'enum', values: ['temperature', 'activity', 'rumination', 'gps'], required: true },
    { name: 'installedAt', type: 'datetime', required: true },
    { name: 'status', type: 'enum', values: ['active', 'inactive', 'faulty'], required: true },
  ],
};

export default Sensor;
